FROM apache/airflow:3.0.5-python3.12
USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         vim \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*


# pyproject.toml dependencies 추가 (Airflow와 함께 설치하여 호환성 보장)
RUN pip install --no-cache-dir \
    "apache-airflow~=3.0.0" \
    "apache-airflow-providers-postgres>=6.2.3" \
    "requests>=2.32.5"

USER airflow